

language: python

matrix:
  include:
    - name: "Python 3.7 on Linux"
      os: linux
      python: 3.7
      dist: xenial
    - name: "Python 3.7 on MacOs"
      os: osx
      osx_image: xcode10.2
      language: shell



before_install:
  - curl https://build.travis-ci.com/files/rustup-init.sh -sSf | sh -s -- -y
  - source $HOME/.cargo/env
  - . $HOME/.cargo/env
  - export PATH=$HOME/.cargo/bin:$PATH


install:
    #   - curl https://sh.rustup.rs -sSf | sh -s -- -y
    #   - source $HOME/.cargo/env
    #   - export PYTHON_LIB=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
    #   - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$PYTHON_LIB:$HOME/rust/lib"
  - python3 setup.py build
  - python3 setup.py build sdist bdist bdist_wheel
    #   - python setup.py sdist
    #   - python setup.py bdist
    #   - python setup.py bdist_wheel
  - python3 setup.py install
    #   - python -c 'import smb'
  - pip3 install -e .

script:
  - python3 -c 'import smb'

