[package]
name = "hic-rs"
version = "0.1.0"
authors = ["fkarg <f.karg10@gmail.com>"]
edition = "2018"


[lib]
name = "string_sum"
crate-type = ["cdylib"]


[dependencies.pyo3]
version = "0.6.0-alpha.4"
features = ["extension-module"]
