[package]
name = "hicrs"
version = "0.1.3"
authors = ["fkarg <f.karg10@gmail.com>"]
edition = "2018"


[lib]
name = "hicrs"
crate-type = ["dylib", "staticlib"]


[dependencies]
num = "0.2.0"
rayon = "1.0.3"
libc = "0.2.58"
